name: Debug

on:
  push:
    branches:
      - WithGitHUB-Workflow

jobs:
  build:
    runs-on: windows-11

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    # You may pin to the exact commit or the version.
    # uses: fawazahmed0/action-debug@9185bd49adec95e03592e3e6036d86f70d5ef423
    - name: Debugging with browser
      uses: fawazahmed0/action-debug@v2
      with:
          # Set credentials in username:password format to access the terminal. Default value is admin:admin
        credentials: admin:admin 
        # optional, default is admin:admin
          
